version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: abb_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd1234$
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:pwd1234$@db:5432/abb_api
      - SECRET_KEY=django-insecure-k-nf3uyrw_^en2o%8e02y0tck&c3@^%28v_jwf4%#2%g54cnuf
      - ALLOWED_HOSTS=localhost

volumes:
  postgres_data:
