# Generated by Django 3.2 on 2024-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
